sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=dev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dev
  include:
    - python: "2.7"
      env: MODE=flake8

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
install:
    - python setup.py install
    - pip install tox coveralls

after_success:
    - coveralls

# command to run tests
script:
    - coverage erase
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}${MODE}
